name:                aoc2020-haskell
version:             0.1.0.0
github:              "lambda-study-group/advent-of-code"
license:             BSD3
author:              "Pedro Castilho"
maintainer:          "cstl.px@gmail.com"
copyright:           "2020 Pedro Castilho"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at https://github.com/lambda-study-group/advent-of-code/blob/main/README.md

dependencies:
- base >= 4.7 && < 5
- text
- vector
- containers

library:
  source-dirs: src

executables:
  aoc2020-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020-haskell

tests:
  aoc2020-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020-haskell
